### ISSUE TITLE
Possible regression in 2.0.0-beta.58: unable to create session.

### ISSUE THREAD

**Issue by emmenko** [iaincollins/next-auth#197]
Ref: #196

I think I found a bug in `2.0.0-beta.58`.

I get:

```
[NextAuth.js][DEBUG] createSession null
CREATE_SESSION_ERROR TypeError: Cannot read property 'id' of null
    at /Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:4545
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:457)
    at f (/Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:656)
    at /Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:768
    at new Promise (<anonymous>)
    at /Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:616
    at E (/Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:4709)
    at D (/Users/emmenko/xxx/node_modules/next-auth/dist/adapters/typeorm/index.js:1:4337)
    at /Users/emmenko/xxx/node_modules/next-auth/dist/server/lib/callback-handler.js:1:2251
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/emmenko/xxx/node_modules/next-auth/dist/server/lib/callback-handler.js:1:411)
    at f (/Users/emmenko/xxx/node_modules/next-auth/dist/server/lib/callback-handler.js:1:610)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

By looking at the code it seems to me that we're passing the wrong value to `createSession`:

https://github.com/iaincollins/next-auth/blob/9c9abf19a36579491b01f1613042f75cafd224a7/src/server/lib/callback-handler.js#L126

Instead of `user`, shouldn't it be `userByProviderAccountId`? 🤔

**Comment by iaincollins** [comment]
Thank you @emmenko! Fixed as `next-auth@2.0.0-beta.59`
