### ISSUE TITLE
Problem with server side getSession()

### ISSUE THREAD

**Issue by nemmtor** [iaincollins/next-auth#334]
**Describe the bug**
Getting error when calling getSession() inside getServerSideProps

**To Reproduce**
You can clone my [repo](https://github.com/nemmtor/super-simple-crm) to reproduce.

I think the problem is here:

```javascript
export async function getServerSideProps({req, res}) {
  const session = await getSession({req});
  if (!session) {
    res.writeHead(301, { Location: '/' });
    res.end();
    return { props: {}};
  }
  const { user } = session;
  return {
    props: { user },
  };
}
```

**Expected behavior**
If there is session - let the user in and pass user object in props, if not then redirect back to homepage.

**Screenshots or error logs**
```
[next-auth][error][CLIENT_FETCH_ERROR] [
  '/api/auth/session',
  TypeError: Only absolute URLs are supported
      at getNodeRequestOptions (/home/nemmtor/webdev/super-simple-crm/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
      at /home/nemmtor/webdev/super-simple-crm/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
      at new Promise (<anonymous>)
      at fetch (/home/nemmtor/webdev/super-simple-crm/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /home/nemmtor/webdev/super-simple-crm/node_modules/next-auth/dist/client/index.js:276:23
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/home/nemmtor/webdev/super-simple-crm/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/home/nemmtor/webdev/super-simple-crm/node_modules/next-auth/dist/client/index.js:22:194)
      at /home/nemmtor/webdev/super-simple-crm/node_modules/next-auth/dist/client/index.js:22:364
      at new Promise (<anonymous>)
] 
https://next-auth.js.org/errors#client_fetch_error
```

**Documentation feedback**

* [x] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
At a glance the code looks okay.

My guess is that you have't defined a value for the the `SITE` environment variable expected in `_app.js`.
