### ISSUE TITLE
Abslute URL error when using getSession method in getServerSideProps

### ISSUE THREAD

**Issue by anthonysapp** [iaincollins/next-auth#335]
**Describe the bug**
when using the getSession method in getServerSideProps, triggers a CLIENT_FETCH_ERROR

**To Reproduce**
Steps to reproduce the behavior.
``` javascript
import { getSession } from "next-auth/client";
```
...
```javascript
export const getServerSideProps = async (ctx) => {
  const session = await getSession(ctx);
  if (!session) {
    const { res } = ctx;
    res.setHeader("location", "/login");
    res.statusCode = 302;
    res.end();
    return;
  }
  return {
    props: { session },
  };
};
```
Include example code (or link to public repository) which can be used to reproduce the behaviour.

**Expected behavior**
Should return the session, if logged in correctly.

**Screenshots or error logs**
[next-auth][error][CLIENT_FETCH_ERROR] [
  '/api/auth/session',
  TypeError: Only absolute URLs are supported
      at getNodeRequestOptions (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
      at /Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
      at new Promise (<anonymous>)
      at fetch (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:276:23
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:22:194)
      at /Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:22:364
      at new Promise (<anonymous>)
      at /Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:22:97
      at _fetchData (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:287:19)
      at /Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:64:25
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/Users/anthony.sapp/Documents/sites/cj-brandbook/node_modules/next-auth/dist/client/index.js:22:194)
] 
https://next-auth.js.org/errors#client_fetch_error

**Additional context**
Code expects an absolute URL, per the error message, but the getSession block here on line 64 of dist/client/index.js generates a url of `/api/auth/session`
```javascript
var session = yield _fetchData("".concat(baseUrl, "/session"), options);
``` 

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
* Make sure you have an  `_app.js` file and the site name is passed correctly.
* See the example project for a working example.

See #334 for an almost identical bug report.
