### ISSUE TITLE
Integration with "Strapi". Having "OAUTH_GET_ACCESS_TOKEN_ERROR" and https://domain/api/auth/error?error=oAuthCallback#_=

### ISSUE THREAD

**Issue by ssuvorov** [iaincollins/next-auth#411]
Hey guys! I'm trying to glue together **next-auth** and [Strapi](https://strapi.io) (Headless CMS).

They have their own Providers plugin for social networks (https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers).

I deployed Strapi to Heroku. Set up a FB provider:
<img width="885" alt="Screenshot 2020-07-08 at 21 31 10" src="https://user-images.githubusercontent.com/3448821/86962043-89bc5b80-c162-11ea-97e3-b2d774f939fa.png">

Regarding documentation, API provides a url for FB login: https://xxx-api.herokuapp.com/connect/facebook. 
I added a direct link for login to my app (haven't added `singin('facebook')`, I believe it's not needed in this case, right?)

```<a href={`${process.env.NEXT_PUBLIC_API_URL}/connect/facebook>login to fb</a>```

When I click on it, Strapi allows me to login on FB and then redirects me back to https://xxx.herokuapp.com/api/auth/error?error=oAuthCallback#_=_ (I guess it redirects to the URL from my screenshot above) and then Next has an error.

And this is what I have in logs

```bash
2020-07-08T19:39:07.957492+00:00 app[web.1]: [next-auth][error][OAUTH_GET_ACCESS_TOKEN_ERROR] [
2020-07-08T19:39:07.957506+00:00 app[web.1]:   {
2020-07-08T19:39:07.957508+00:00 app[web.1]:     statusCode: 400,
2020-07-08T19:39:07.957509+00:00 app[web.1]:     data: '{"error":{"message":"Invalid verification code format.","type":"OAuthException","code":100,"fbtrace_id":"AjMKCKRMG3lxp9TokjMbbLx"}}'
2020-07-08T19:39:07.957509+00:00 app[web.1]:   },
2020-07-08T19:39:07.957510+00:00 app[web.1]:   undefined,
2020-07-08T19:39:07.957510+00:00 app[web.1]:   undefined
2020-07-08T19:39:07.957510+00:00 app[web.1]: ] 
2020-07-08T19:39:07.957511+00:00 app[web.1]: https://next-auth.js.org/errors#oauth_get_access_token_error
2020-07-08T19:39:07.957639+00:00 app[web.1]: [next-auth][error][OAUTH_GET_ACCESS_TOKEN_ERROR] [
2020-07-08T19:39:07.957639+00:00 app[web.1]:   {
2020-07-08T19:39:07.957640+00:00 app[web.1]:     statusCode: 400,
2020-07-08T19:39:07.957640+00:00 app[web.1]:     data: '{"error":{"message":"Invalid verification code format.","type":"OAuthException","code":100,"fbtrace_id":"AjMKCKRMG3lxp9TokjMbbLx"}}'
2020-07-08T19:39:07.957640+00:00 app[web.1]:   },
2020-07-08T19:39:07.957641+00:00 app[web.1]:   undefined,
2020-07-08T19:39:07.957641+00:00 app[web.1]:   'facebook',
2020-07-08T19:39:07.957641+00:00 app[web.1]:   undefined
2020-07-08T19:39:07.957641+00:00 app[web.1]: ] 
2020-07-08T19:39:07.957642+00:00 app[web.1]: https://next-auth.js.org/errors#oauth_get_access_token_error
2020-07-08T19:39:08.076013+00:00 app[web.1]: [next-auth][error][OAUTH_GET_PROFILE_ERROR] [
2020-07-08T19:39:08.076014+00:00 app[web.1]:   {
2020-07-08T19:39:08.076015+00:00 app[web.1]:     statusCode: 401,
2020-07-08T19:39:08.076016+00:00 app[web.1]:     data: '{"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"A-psP1x5lPb2X74XsrnAJkW"}}'
2020-07-08T19:39:08.076016+00:00 app[web.1]:   }
2020-07-08T19:39:08.076016+00:00 app[web.1]: ] 
2020-07-08T19:39:08.076017+00:00 app[web.1]: https://next-auth.js.org/errors#oauth_get_profile_error
2020-07-08T19:39:08.076385+00:00 app[web.1]: [next-auth][error][OAUTH_PARSE_PROFILE_ERROR] [
2020-07-08T19:39:08.076386+00:00 app[web.1]:   TypeError: Cannot read property 'id' of undefined
2020-07-08T19:39:08.076387+00:00 app[web.1]:       at Object.profile (/app/node_modules/next-auth/dist/providers/facebook.js:26:22)
2020-07-08T19:39:08.076388+00:00 app[web.1]:       at /app/node_modules/next-auth/dist/server/lib/oauth/callback.js:136:32
2020-07-08T19:39:08.076388+00:00 app[web.1]:       at Generator.next (<anonymous>)
2020-07-08T19:39:08.076389+00:00 app[web.1]:       at asyncGeneratorStep (/app/node_modules/next-auth/dist/server/lib/oauth/callback.js:24:103)
2020-07-08T19:39:08.076389+00:00 app[web.1]:       at _next (/app/node_modules/next-auth/dist/server/lib/oauth/callback.js:26:194)
2020-07-08T19:39:08.076389+00:00 app[web.1]:       at /app/node_modules/next-auth/dist/server/lib/oauth/callback.js:26:364
2020-07-08T19:39:08.076390+00:00 app[web.1]:       at new Promise (<anonymous>)
2020-07-08T19:39:08.076390+00:00 app[web.1]:       at /app/node_modules/next-auth/dist/server/lib/oauth/callback.js:26:97
2020-07-08T19:39:08.076390+00:00 app[web.1]:       at _getProfile (/app/node_modules/next-auth/dist/server/lib/oauth/callback.js:120:23)
2020-07-08T19:39:08.076391+00:00 app[web.1]:       at /app/node_modules/next-auth/dist/server/lib/oauth/callback.js:78:25,
2020-07-08T19:39:08.076391+00:00 app[web.1]:   undefined
2020-07-08T19:39:08.076394+00:00 app[web.1]: ] 
2020-07-08T19:39:08.076394+00:00 app[web.1]: https://next-auth.js.org/errors#oauth_parse_profile_error
2020-07-08T19:39:08.076758+00:00 app[web.1]: [next-auth][error][CALLBACK_OAUTH_ERROR] [
2020-07-08T19:39:08.076758+00:00 app[web.1]:   {
2020-07-08T19:39:08.076758+00:00 app[web.1]:     statusCode: 401,
2020-07-08T19:39:08.076759+00:00 app[web.1]:     data: '{"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"A-psP1x5lPb2X74XsrnAJkW"}}'
2020-07-08T19:39:08.076759+00:00 app[web.1]:   }
2020-07-08T19:39:08.076760+00:00 app[web.1]: ] 
2020-07-08T19:39:08.076760+00:00 app[web.1]: https://next-auth.js.org/errors#callback_oauth_error
2020-07-08T19:39:08.141464+00:00 heroku[router]: at=info method=GET path="/api/auth/error?error=oAuthCallback" host=xxx.herokuapp.com request_id=354bda12-1265-41e4-8c2b-efd6e83fb2de fwd="78.54.75.4" dyno=web.1 connect=1ms service=4ms status=200 bytes=1325 protocol=https
2020-07-08T19:39:08.076619+00:00 heroku[router]: at=info method=GET path="/api/auth/callback/facebook?access_token=srEuQDYgIt5TReMe1UojyLG4WPZAjV8YLRXzdixF18qA9WSeQX1tCtqvAoUJky24YRL4G9sMIaP3qf9rdbH0fwcPEok1oOsdtoLOtzOrAYNrsEcWgsLZCf&raw%5Btoken_type%5D=bearer&raw%5Bexpires_in%5D=5182370" host=xxx.herokuapp.com request_id=4d63-4170-803a-f652f41e68e2 fwd="78.54.75.4" dyno=web.1 connect=0ms service=245ms status=302 bytes=191 protocol=https
```

Could you help me to identify the problem, plz?

**Comment by iaincollins** [comment]
Hi there! It looks like Strapi has it's own completely different authentication system.

I might be wrong, but I don't think NextAuth.js and Strapi can be integrated (at least not in this way!).

**Comment by iaincollins** [comment]
I'm going to close this as I don't think we can help - but if you get in touch with them and/or find out anything interesting please do update this!

**Comment by ssuvorov** [comment]
@iaincollins sure. Thank you!
