### ISSUE TITLE
Error: only absolute urls are supported

### ISSUE THREAD

**Issue by sisardor** [iaincollins/next-auth#82]
Getting this error
```
NextAuth Error Loading Providers
Error: only absolute urls are supported
    at /Users/sisardor/Github/next-gemex/node_modules/node-fetch/index.js:54:10
    at new Promise (<anonymous>)
    at new Fetch (/Users/sisardor/Github/next-gemex/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/sisardor/Github/next-gemex/node_modules/node-fetch/index.js:37:10)
    at module.exports (/Users/sisardor/Github/next-gemex/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at Function._callee4$ (/Users/sisardor/Github/next-gemex/node_modules/next-auth/client.js:256:53)
    at tryCatch (/Users/sisardor/Github/next-gemex/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/sisardor/Github/next-gemex/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sisardor/Github/next-gemex/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)

```

Server side fetching session failing

Code: 
```js
export default class Admin extends React.Component {
  static async getInitialProps({ ctx, req }) {

    const session =  await NextAuth.init({req});
    const providers = await NextAuth.providers({req})
    // console.log('providers', providers);
    if (!session.user) {
      // Already signed in? No need to continue.
      // Throw them back to the main page
      redirect(ctx, '/')
      return {}
    }
    // console.log(session);
    return {
      session,// await NextAuth.init({req}),// Add this.props.session to all pages
      lang: 'en', // Add a lang property to all pages for accessibility
      providers
    }
  }
```

**Comment by iaincollins** [comment]
Sorry for lack of quicker response.

The error here was triggered by `NextAuth.providers()`but I'm not sure why, as it looks like it is being passed a `req` object correctly so should not trigger this error.

It *seems* like somehow the `req` object was not populated when running server side, but that should not be the case (perhaps an issue with a custom server implementation??).

Closing this as is address in the upcoming 2.0 release, which has new flows for client and server side which should help avoid issues like this.
