### ISSUE TITLE
CSRF token missing

### ISSUE THREAD

**Issue by ndom91** [iaincollins/next-auth#88]
So I've got this odd issue since I've changed domains. 

I was developing at `applicationname.dev` for the first month or two, now I've migrated to `applicationname.de`, and whenever I made this my logs began filling up with `Error: CSRF token missing` errors on every request. 

I haven't changed anything to the `next-auth` implementation or anything else. I also double checked the state's session object, csrf token is in there and seems to be valid. 

Is there anywhere else I can debug this? I'm cant seem to ifnd a way forward here.. 

FYI - Here's the rest of the error message by the way:
```
Error: CSRF token missing
    at checkCsrf (/opt/newtelco/next-maintenance/node_modules/lusca/lib/csrf.js:151:18)
    at Layer.handle [as handle_request] (/opt/newtelco/next-maintenance/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:317:13)
    at /opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:275:10)
    at session (/opt/newtelco/next-maintenance/node_modules/express-session/index.js:468:7)
    at Layer.handle [as handle_request] (/opt/newtelco/next-maintenance/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:317:13)
    at /opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/opt/newtelco/next-maintenance/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/opt/newtelco/next-maintenance/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:317:13)
    at /opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/newtelco/next-maintenance/node_modules/express/lib/router/index.js:275:10)
    at /opt/newtelco/next-maintenance/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/opt/newtelco/next-maintenance/node_modules/raw-body/index.js:224:16)
    at done (/opt/newtelco/next-maintenance/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/opt/newtelco/next-maintenance/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:197:13)
    at IncomingMessage.EventEmitter.emit (domain.js:439:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Thanks!

**Comment by ndom91** [comment]
Disappeared with an update to nextjs 9.1.2
